# Use the official lightweight Python image.
FROM python:3.12-slim

ARG DEPS=requirements.api.txt

# Set the working directory
WORKDIR /app

# Copy the project files to the container
ADD jaaspr /app/jaaspr
COPY $DEPS .

# Install dependencies with Poetry
RUN pip install -r $DEPS

# Expose port for Flask
EXPOSE $FLASK_RUN_PORT

# Start the Flask app
CMD ["sh", "-c", "waitress-serve --port=$FLASK_RUN_PORT $FLASK_APP"]
